//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDV_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Jobs = new HashSet<Job>();
            this.Name = "N/A";
            this.Surname = "N/A";
            this.Address = "N/A";
            this.City = "N/A";
            this.PostalCode = "N/A";
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
