//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDV_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Job_Employee = new HashSet<Job_Employee>();
            this.EmployeeID = "N/A";
            this.Name = "N/A";
            this.Surname = "N/A";
        }
    
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<Job_Employee> Job_Employee { get; set; }
    }
}
