//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDV_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Job_Employee = new HashSet<Job_Employee>();
            this.Job_Material = new HashSet<Job_Material>();
            this.Days = 0;
        }
    
        public int JobCardID { get; set; }
        public int CustomerID { get; set; }
        public int JobTypeID { get; set; }
        public int Days { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual ICollection<Job_Employee> Job_Employee { get; set; }
        public virtual ICollection<Job_Material> Job_Material { get; set; }
    }
}
