//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDV_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobType
    {
        public JobType()
        {
            this.Jobs = new HashSet<Job>();
            this.JobType1 = "N/A";
            this.Rate =0;
        }
    
        public int JobTypeID { get; set; }
        public string JobType1 { get; set; }
        public decimal Rate { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
