//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDV_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Job_Material = new HashSet<Job_Material>();
            this.Description = "N/A";
        }
    
        public int MaterialID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Job_Material> Job_Material { get; set; }
    }
}
