//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDV_Framework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Domingo_Roof_WorksEntities : DbContext
    {
        public Domingo_Roof_WorksEntities()
            : base("name=Domingo_Roof_WorksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Job_Employee> Job_Employee { get; set; }
        public DbSet<Job_Material> Job_Material { get; set; }
        public DbSet<JobType> JobTypes { get; set; }
        public DbSet<Material> Materials { get; set; }
    }
}
